### PR TITLE
process variable in PhantomJS fix

### PR DESCRIPTION
**Pull request by EugeneSnihovsky**
A simple fix, that able to use your module in PhantomJS and avoid this error:

error screenshow

### CODE REVIEW

**Comment by EugeneSnihovsky** [comment]
For example, [pouchDB](https://pouchdb.com) and plugins for it use your module and all works like a charm. But last version of [ionic-2](http://ionicframework.com/docs/v2/) used webpack and unit tests fail with error on image above during compilation. I can't figure out is it problem of webpack, or PhantomJS or your module but this fix helps.
If I wrong locate problem - sorry to trouble you.

**Comment by calvinmetcalf** [comment]
I know the problem, it's with webpack inexplicitly giving preference to component.json over package.json, nobody uses component any more so I'll just remove that

**Comment by calvinmetcalf** [comment]
wait no, that's not it, the package manager that nobody uses that caused problems was jam onot component, um so this is definitly a webpack problem, we intentionally make a version available at lib/browser.js that doesn't have  process, I don't know why it's not being included

**Comment by calvinmetcalf** [comment]
this is a webpack issue causing it to load the wrong file, if you post your config I may be able to help, but you probably want to talk to the webpack people

**Pull request closed without merging**
